
28/07/2020 09:10:28 - Falha interna da função <b>MCONTROL_OEE.ReadDBGETVIEWERVERSION</b>
28/07/2020 09:10:28 - System.Data.SqlClient.SqlException (0x80131904): Erro de rede ou específico à instância ao estabelecer conexão com o SQL Server. O servidor não foi encontrado ou não estava acessível. Verifique se o nome da instância está correto e se o SQL Server está configurado para permitir conexões remotas. (provider: TCP Provider, error: 0 - O tempo limite de espera foi atingido.) ---> System.ComponentModel.Win32Exception (0x80004005): O tempo limite de espera foi atingido
   em System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   em System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   em System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   em System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   em System.Data.SqlClient.SqlConnection.Open()
   em MCONTROL_OEE.mod_OEE.ReadDBGETVIEWERVERSION(String strVERSION, String strBUILD, Boolean& bolNEW, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 386
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:258,State:0,Class:20
28/07/2020 09:13:43 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 09:13:43 - System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIAL, String strDATAFINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10905
28/07/2020 09:43:13 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 09:43:13 - System.FormatException: Cadeia de caracteres não foi reconhecida como DateTime válido.
   em System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   em System.Convert.ToDateTime(String value)
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIAL, String strDATAFINAL, String& strERROR)
28/07/2020 09:51:18 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 09:51:18 - System.FormatException: Cadeia de caracteres não foi reconhecida como DateTime válido.
   em System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   em System.Convert.ToDateTime(String value)
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIAL, String strDATAFINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10833
28/07/2020 09:52:15 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 09:52:15 - System.FormatException: Cadeia de caracteres não foi reconhecida como DateTime válido.
   em System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   em System.Convert.ToDateTime(String value)
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIAL, String strDATAFINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10833
28/07/2020 09:54:00 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 09:54:00 - System.FormatException: Cadeia de caracteres não foi reconhecida como DateTime válido.
   em System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   em System.Convert.ToDateTime(String value)
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIAL, String strDATAFINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10833
28/07/2020 10:55:38 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 10:55:38 - System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIALORIGINAL, String strDATAFINALORIGINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10919
28/07/2020 11:27:05 - Falha interna da função WriteDBREPORTTEMPOCALENDARIO
28/07/2020 11:27:05 - System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTTEMPOCALENDARIO(ListBoxAdv lbMAQUINA, ListBoxAdv lbMAQUINAID, String strDATAINICIALORIGINAL, String strDATAFINALORIGINAL, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10921
28/07/2020 23:16:54 - Falha interna da função WriteDBREPORTAPONTAMENTO_GRUPO
28/07/2020 23:16:54 - System.Data.SqlClient.SqlException (0x80131904): Tempo Limite de Execução Expirado.  O período de tempo limite terminou antes da conclusão da operação ou o servidor não está respondendo. ---> System.ComponentModel.Win32Exception (0x80004005): O tempo limite de espera foi atingido
   em System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   em System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   em System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   em System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   em System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   em System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   em System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   em System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   em System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   em System.Data.SqlClient.SqlDataReader.get_MetaData()
   em System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   em System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   em System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   em System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   em System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   em System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   em System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   em System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   em System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   em System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, String srcTable)
   em MCONTROL_OEE.mod_OEE.WriteDBREPORTAPONTAMENTO_GRUPO(Int32 intUSERID, Int32 intMES, Int32 intANO, String& strERROR) na D:\VOESTALPINE - DEV\MCONTROL_OEE\MCONTROL_OEE\mod_OEE.vb:linha 10333
ClientConnectionId:cceaa054-671e-4438-bac3-a457356414e7
Error Number:-2,State:0,Class:11